loaders:
  gcloudcli: ~
  textfile: 
    path: "urls.txt"
summaryintervals:
  - title: "yesterday"
    distancehours: 24
    ansii: "green+h:black"
  - title: "last week"
    distancehours: 168
    ansii: "red+h:black"
  - title: "last month"
    distancehours: 720
    ansii: "blue+h:black"
reports:
  ascii: ~
  mailgun:
    privatekey: "api:something"
    domain: "something.com"
    from: "Lockdown Tracker <postmaster@something.com>"
    to: "Sysadmins <sysadmin@something.com>"
    subj: "Lockdown status report"
    templatepath: "./reports/tmpl/email/"
storage:
  json:
    path: "../tmp/data.json" # folder must exist
    recordlimit: 100 # careful: this could truncate an existing file
