loaders:
  gcloudcli: ~
  textfile: 
    path: "urls.txt"
summaryintervals:
  - title: "yesterday"
    distancedays: 1
  - title: "last week"
    distancedays: 7
  - title: "last month"
    distancedays: 30
reports:
  ascii: ~
  mailgun:
    privatekey: "api:something"
    domain: "something.com"
    from: "Lockdown Tracker <postmaster@something.com>"
    to: "Sysadmins <sysadmin@something.com>"
    subj: "Lockdown status report"
storage:
  json:
    path: "../tmp/data.json" # folder must exist
    recordlimit: 100 # careful: this could truncate an existing file
